services:
  - type: web
    name: toursphere-api
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: DATABASE
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 90d
      - key: JWT_COOKIE_EXPIRES_IN
        value: 90
      - key: FRONTEND_URL
        sync: false
